# Generated by Django 5.0.4 on 2024-04-15 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabella',
            name='sinonimi',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='campo',
            name='sinonimi',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tabella',
            name='struttura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin.strutturadatabase'),
        ),
    ]
