name: Django CI

on:
  workflow_dispatch:
    inputs:
      environment:
        type: string
        default: DEV
        required: true
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      working-directory: ./src/chatSQL
      run: |
        python -m pip install --upgrade pip
        python -m pip install Django
        python -m pip install coveralls
        python -m pip install prospector
    - name: Static Test
      uses: jpetrucciani/prospector-check@1.10.3
    - name: Run Tests
      working-directory: ./src/chatSQL
      run: |
        coverage run --source='.' manage.py test
    - name: Test Coverage
      uses: coverallsapp/github-action@v2.2.3